#Student--------------------------------

CREATE TABLE student.STUDENT(
  USN VARCHAR(10) PRIMARY KEY,
  SNAME VARCHAR(25),
  ADDRESS VARCHAR(25),
  PHONE INT(10),
  GENDER CHAR(1)
);
desc student.STUDENT;


#SEMSEC----------------------------------

CREATE TABLE student.SEMSEC(
SSID VARCHAR(5) PRIMARY KEY,
SEM INT(2),
SEC CHAR(1));
desc student.SEMSEC;


#Subject ---------------------------------

CREATE TABLE student.SUBJECT (
SUBCODE VARCHAR(8) ,
TITLE VARCHAR(20) NOT NULL,
SEM INT(2),
CREDITS INT(2),
PRIMARY KEY (SUBCODE));
desc student.SUBJECT;

#IAMARKS---------------------------------

CREATE TABLE student.IAMARKS(
USN VARCHAR(10),
SUBCODE VARCHAR(8),
SSID VARCHAR(5),
TEST1 INT(2),
TEST2 INT(2),
TEST3 INT(2),
FINALIA INT(2),
FOREIGN KEY (USN) REFERENCES STUDENT (USN),
FOREIGN KEY (SUBCODE) REFERENCES SUBJECT (SUBCODE),
FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));
desc student.IAMARKS;

#Class------------------------------------

CREATE TABLE student.CLASS(
USN VARCHAR(10),
SSID VARCHAR(5),
FOREIGN KEY(USN) REFERENCES STUDENT(USN),
FOREIGN KEY(SSID) REFERENCES IAMARKS(SSID));
desc student.CLASS;
